/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JmPrsh153 (https://sketchfab.com/JmPrsh153)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golf-ball-lp-aa9182956c494e7e92c3fde035a0997a
Title: Golf Ball LP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import golfBallModel from '../assets/3d/golf_ball_lp.glb'

const GolfBall = (props) => {
    const { nodes, materials } = useGLTF(golfBallModel)

    return (
        <group {...props} dispose={null} scale={.5}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_2.geometry}
                material={materials.lambert2SG}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload(golfBallModel)

export default GolfBall;